name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  VERSION: "4.1.0.${{github.run_number}}"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: '6.0.x'

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: dotnet restore Source/mqttHub.sln

      # Build applications
      - name: Build win-x86
        run: dotnet publish Source/mqttHub.csproj -r win-x86 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip win-x86 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/win-x86/publish/
          dest: mqttHub-windows-x86.zip

      - name: Collect win-x86 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-windows-x86
          path: ${{ github.workspace }}/mqttHub-windows-x86.zip

      - name: Build win-x64
        run: dotnet publish Source/mqttHub.csproj -r win-x64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip win-x64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/win-x64/publish/
          dest: mqttHub-windows-x64.zip

      - name: Collect win-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-windows-x64
          path: ${{ github.workspace }}/mqttHub-windows-x64.zip

      - name: Build win-arm
        run: dotnet publish Source/mqttHub.csproj -r win-arm -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip win-arm build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/win-arm/publish/
          dest: mqttHub-windows-ARM.zip

      - name: Collect win-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-windows-arm
          path: ${{ github.workspace }}/mqttHub-windows-arm.zip

      - name: Build win-arm64
        run: dotnet publish Source/mqttHub.csproj -r win-arm64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip win-arm64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/win-arm64/publish/
          dest: mqttHub-windows-ARM64.zip

      - name: Collect win-arm64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-windows-arm64
          path: ${{ github.workspace }}/mqttHub-windows-arm64.zip

      - name: Build osx-x64
        run: dotnet publish Source/mqttHub.csproj -r osx.12-x64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false -p:IncludeAllContentForSelfExtract=true --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip osx-x64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/osx.12-x64/publish/
          dest: mqttHub-macOS-X64.zip

      - name: Collect osx-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-macOS-x64
          path: ${{ github.workspace }}/mqttHub-macOS-x64.zip

      - name: Build osx-arm64
        run: dotnet publish Source/mqttHub.csproj -r osx.12-arm64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false -p:IncludeAllContentForSelfExtract=true --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip osx-arm64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/osx.12-arm64/publish/
          dest: mqttHub-macOS-ARM64.zip

      - name: Collect osx-arm64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-macOS-arm64
          path: ${{ github.workspace }}/mqttHub-macOS-arm64.zip

      - name: Build linux-x64
        run: dotnet publish Source/mqttHub.csproj -r linux-x64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip linux-x64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/linux-x64/publish/
          dest: mqttHub-linux-x64.zip

      - name: Collect linux-x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-linux-x64
          path: ${{ github.workspace }}/mqttHub-linux-X64.zip

      - name: Build linux-arm
        run: dotnet publish Source/mqttHub.csproj -r linux-arm -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip linux-arm build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/linux-arm/publish/
          dest: mqttHub-linux-arm.zip

      - name: Collect linux-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-linux-arm
          path: ${{ github.workspace }}/mqttHub-linux-arm.zip

      - name: Build linux-arm64
        run: dotnet publish Source/mqttHub.csproj -r linux-arm64 -p:Configuration=Release -p:PublishSingleFile=false -p:PublishReadyToRun=true -p:IncludeNativeLibrariesForSelfExtract=false --self-contained true -property:Version=${{ env.VERSION }}

      - name: Zip linux-arm64 build
        uses: vimtor/action-zip@v1
        with:
          files: Source/bin/Release/linux-arm64/publish/
          dest: mqttHub-linux-arm64.zip

      - name: Collect linux-arm artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-linux-arm64
          path: ${{ github.workspace }}/mqttHub-linux-arm64.zip

      # Debian package
      - name: Set up installation directory
        run: mkdir -p packaging/opt/mqttHub

      - name: Copy meta data
        run: |
          cp -R Build/deb-meta/* packaging/
          chmod 755 packaging/DEBIAN/postinst
          chmod 755 packaging/DEBIAN/postrm
          chmod 755 packaging/DEBIAN/prerm

      - name: Move artifacts to packaging directory
        run: cp -R Source/bin/Release/linux-x64/publish/* packaging/opt/mqttHub

      - name: Adjust files
        run: |
          rm packaging/opt/mqttHub/appsettings.Development.json
          mv packaging/opt/mqttHub/appsettings.json packaging/opt/mqttHub/appsettings.template.json

      - name: Adjust permissions
        run: |
          cd packaging/opt/mqttHub
          find . -type f | xargs chmod -R 644
          chmod 755 mqttHub

      - name: Generate MD5s
        run: |
          cd packaging/          
          md5sum $(find * -type f -not -path 'DEBIAN/*') > DEBIAN/md5sums

      - name: Patch meta
        run: sed -i 's/\VERSIONPLACEHOLDER/${{ env.VERSION }}/' packaging/DEBIAN/control

      - name: Package everything
        run: dpkg-deb -v --build packaging/ mqttHub-${{ env.VERSION }}-amd64.deb

      - name: Save .deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: mqttHub-${{ env.VERSION }}-amd64.deb
          path: mqttHub-${{ env.VERSION }}-amd64.deb

      # Release Management
      - name: Delete release drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        with:
          threshold: 1s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true
          files: |
            ${{ github.workspace }}/mqttHub-windows-x86.zip
            ${{ github.workspace }}/mqttHub-windows-x64.zip
            ${{ github.workspace }}/mqttHub-windows-arm.zip
            ${{ github.workspace }}/mqttHub-windows-arm64.zip
            ${{ github.workspace }}/mqttHub-macOS-x64.zip
            ${{ github.workspace }}/mqttHub-macOS-arm64.zip
            ${{ github.workspace }}/mqttHub-linux-x64.zip
            ${{ github.workspace }}/mqttHub-linux-arm.zip
            ${{ github.workspace }}/mqttHub-linux-arm64.zip